################################################################################
#                       GENERAL PARAMETERS SECTION                             # 
#------------------------------------------------------------------------------#
# The general parameters section defines parameters that are global or general #
# for the complete workflow.                                                   #
################################################################################

#                             Mapping File                                     #
#------------------------------------------------------------------------------#
# Location of the mapping file                                                 #
# The mapping file should be a tab separated file with the following columns:  #
# sample	taxonID   path                                                       #
# the sample names can contain letters, numbers and , "-"                      #
# do not use spaces in the file paths                                          #
#------------------------------------------------------------------------------#
samples_file: mapping.tsv


#------------------------------------------------------------------------------#
#                             Output folder Name                               #
#------------------------------------------------------------------------------#
# The name of the output folder. Results will                                  #
# be found in results/projects> after a successful run                         #
#------------------------------------------------------------------------------#
output_folder:            "results/v2"


#------------------------------------------------------------------------------#
#                             Parameter settings                               #
#------------------------------------------------------------------------------#
# Settings used for  pafCoordsDotPlotly                                       #
# be found in results/projects> after a sucessful run                         #
#------------------------------------------------------------------------------#
minimap2:
  asm-preset: "asm20" # preset for minimap2 alignment, options are:
                    # asm5:  Use this if the average divergence is not much higher than 0.1%. 
                    # asm10: Use this if the average divergence is around 1%.
                    # asm20: Use this if the average divergence is around several %.

pafCoordsDotPlotly:
  min-alignment-length: 100 # filter alignments less than cutoff X bp
  min-query-length: 100 # filter queries with total alignments less than cutoff X bp